name: Undeploy Treafik

on: workflow_dispatch

env:
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1

jobs:
  deploy_traefik:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      - name: Undeploy
        run: |-
          helm uninstall traefik
          kubectl get services -o wide
